Use native promises
TF2Autobot/tf2autobot pull request #1171
Opened 2022-06-16 02:40 UTC by carlosliam

Refactored the code to use native promises and remove a few dependencies.

2022-06-16 02:50 UTC, idinium96 commented
Thank you. I will have a look on this and solve the conflict once I'm back home.

2022-06-17 15:33 UTC, idinium96 commented
Works now.
Previously it just never initializes bptf-listings.

2022-06-17 17:01 UTC, idinium96 requested changes
Looks like the process is not terminated when there's an error on start, and it will just stuck there indefinitely.
![image](https://user-images.githubusercontent.com/47635037/174344022-db104780-e948-4483-a1bf-28eb33f19818.png)

2022-06-17 17:05 UTC, idinium96 requested changes
Stopping the bot also does not immediately terminate the process while it's starting, like how it used to be.
![image](https://user-images.githubusercontent.com/47635037/174345144-6c677676-1fb5-4847-8f9a-fb1159277c6f.png)

2022-06-17 17:34 UTC, carlosliam commented on src/classes/Bot.ts
> +        };
This function is called in between each promise in the chain and should handle any shutdowns/signals by throwing an error, skipping any further promises added using `.then(func)`. I'm not sure why it's not working.

2022-06-17 17:38 UTC, carlosliam commented
I think returning the promise from the `start` function should fix the error handling issue. Just added a commit which does that.

2022-06-17 17:53 UTC, idinium96 commented
nah.
![image](https://user-images.githubusercontent.com/47635037/174351834-bf240811-0684-4937-8d77-b0bd42c1ab11.png)

I think should have `catch` here.
https://github.com/TF2Autobot/tf2autobot/blob/aaf13c5500531c65444945a3353e524c7f260ccd/src/app.ts#L144-L152

`.catch(err => throw err));`

2022-06-17 18:36 UTC, idinium96 commented
The process is still not terminated/crashed when there's an error on start.
![image](https://user-images.githubusercontent.com/47635037/174357865-782e598e-082c-4196-81be-a20f3e59a548.png)

2022-06-17 18:42 UTC, carlosliam commented
Can you place a log statement before line 734 in `src/classes/Bot.ts` to see if the `checkIfStopping` function is being run after each promise in the chain?

2022-06-17 18:44 UTC, idinium96 commented
Sure thing. Let me try.
Also, if you want to use my extra account reserved for testing, just let me know.

2022-06-17 18:56 UTC, idinium96 commented
![image](https://user-images.githubusercontent.com/47635037/174385071-62bec8f2-da48-4331-b2b9-b93743d6268f.png)

The old one should be here that will reject the `start`
https://github.com/TF2Autobot/tf2autobot/blob/f8f7c9a49bd92faad0cd6da9b5b4b1c5c20d3283/src/classes/Bot.ts#L1028-L1031

I am also not sure if using `let promise = Promise.resolve();` is the right way to do or not.

2022-06-17 18:59 UTC, idinium96 commented
Maybe bring back
https://github.com/TF2Autobot/tf2autobot/blob/f8f7c9a49bd92faad0cd6da9b5b4b1c5c20d3283/src/classes/Bot.ts#L735
https://github.com/TF2Autobot/tf2autobot/blob/f8f7c9a49bd92faad0cd6da9b5b4b1c5c20d3283/src/classes/BotManager.ts#L58

and reject on error, so that it will `catch` the error in `app.js`

2022-06-17 19:31 UTC, carlosliam commented
I am unable to reproduce these issues on my machine at the current commit. I tried with node v16.15.1 and node v18.4.0.

2022-06-18 00:05 UTC, idinium96 commented
If you're unable to reproduce the error, that means Steam is back alive.
Try adding a line that will throw an error anywhere in the promiseChains, like the one I previously did.

2022-06-19 23:50 UTC, carlosliam commented
I can't reproduce even when manually introducing an error - the code correctly shuts down upon erroring on my machine. See the attached mov file.

https://user-images.githubusercontent.com/3758364/174504862-dd2f43b0-a871-494b-af27-66d90a6f89db.mov

2022-06-21 07:01 UTC, idinium96 commented
hhmmmm weird.

2022-07-07 01:13 UTC, idinium96 approved these changes

2022-07-07 01:13 UTC, idinium96 commented
Merging this into development.
Thank you very much!

2022-07-07 02:36 UTC, merged